name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login docker.pkg.github.com -u cgranade -p ${{ secrets.GITHUB_PACKAGE_TOKEN }}
    - name: Build and push Docker image
      run: |
        $ImageTag = "$([DateTime]::Now.Ticks)"
        docker build qsharp-rise --tag qsharp-rise:$ImageTag
        docker tag qsharp-rise:$ImageTag docker.pkg.github.com/cgranade/misc-containers/qsharp-rise:$ImageTag
        docker push docker.pkg.github.com/cgranade/misc-containers/qsharp-rise:$ImageTag
      shell: pwsh
