name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build qsharp-rise --tag qsharp-rise:$(date +%s)
    - name: Docker login
      run: docker login docker.pkg.github.com -u cgranade -p ${{ secrets.GITHUB_TOKEN }}
    - name: Docker tag
      run: docker tag qsharp-rise:$(date +%s) docker.pkg.github.com/cgranade/misc-containers/qsharp-rise:$(date +%s)
    - name: Docker push
      run: docker push docker.pkg.github.com/cgranade/misc-containers/qsharp-rise:$(date +%s)
 
