name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Set environment variables
      run: $Env:IMAGE_TAG = "$([DateTime]::Now.Ticks)"
      shell: pwsh
    - name: Docker login
      run: docker login docker.pkg.github.com -u cgranade -p ${{ secrets.GITHUB_PACKAGE_TOKEN }}
    - name: Build the Docker image
      run: docker build qsharp-rise --tag qsharp-rise:${Env:IMAGE_TAG}
      shell: pwsh
    - name: Docker tag
      run: docker tag qsharp-rise:${IMAGE_TAG} docker.pkg.github.com/cgranade/misc-containers/qsharp-rise:${IMAGE_TAG}
    - name: Docker push
      run: docker push docker.pkg.github.com/cgranade/misc-containers/qsharp-rise:${IMAGE_TAG}
 
